config/routes.rb
Rails.application.routes.draw do
	
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

	root "welcome#index"
	resources :annonces
	resources :categories
	get "/mes_annonces", to: "mes_annonces#index"
	get "/static/cgu", to: "static#cgu"
	get "/static/a_propos", to: "static#a_propos"
	get "/list", to: "static#list"
	get "admin", to: 'welcome#admin'
	get "contact", to: "contact#simple_form"
	resources :news

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

	before_action :find_news, only: [:show, :edit, :update, :destroy]

	def index
		@new = News.all.order("created_at DESC")
	end

	def new
		@new = News.new
	end

	def create
		@new = News.new(news_params)
		if @new.save
			redirect_to news_index_path, notice: "Article créé avec succès !"
		else
			render 'new', notice: "Oups ! Une erreur s'est produite..."
		end
	end


	def edit
	end

	def update
		if @new.update(news_params)
			redirect_to @new, notice: "Article éditée avec succès !"
		else
			render 'edit'
		end
	end

	def show
		
	end

	def destroy
		@new.destroy
		redirect_to news_index_path, notice: "Article supprimée"
	end

	private 
		def news_params
			params.require(:news).permit(:id, :titre, :contenu)
		end

	private
		def find_news
			@new = News.find(params[:id])
		end

end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/edit.html.erb
<div class="container">
	<%= form_for :news, url:news_index_path(@new),  method: :patch do |f| %>

	<div>
	<%= f.label :titre, "Titre *" %>
	<%= f.text_field :titre, {class: "form-control input-lg"} %>
	</div><br>

	<div>
	<p>
    <%= f.label :contenu, "Contenu *" %><br>
    <%= f.text_area :contenu,  {class: "form-control input-lg"}%>
 	</p>
	</div><br>

	<%= f.submit "Créer", class:"btn btn-primary" %>
	<%end%>
</div>

app/views/news/index.html.erb
<div class="container">
	<h1>Liste des articles</h1>
	<table class='table table-hover'>
		<tr class="info">
			<th>Titre</th>
			<th>Contenu</th>
			<th>Date de création</th>
			<th>Actions</th>
		</tr>
		<% @new.each do |news| %>
		<tr>
			<td><%=news.titre%></td>
			<td><%=news.contenu%></td>
			<td><%=news.created_at%></td>
			<td><%=link_to 'Éditer', edit_news_path(news)%> | <%= link_to "Supprimer", news_path(news), method: :delete, data: { confirm: "êtes vous sur ?"} %></td>
		</tr>
		<%end%>
	</table>
<%= link_to "Nouvel article", new_news_path %>
</div>

app/views/news/new.html.erb
<div class="container">
	<h1>Nouvelle annonce</h1>

	<%= form_for :news, url:news_index_path do |f| %>

	<div>
	<%= f.label :titre, "Titre *" %>
	<%= f.text_field :titre, {class: "form-control input-lg"} %>
	</div><br>

	<div>
	<p>
    <%= f.label :contenu, "Contenu *" %><br>
    <%= f.text_area :contenu,  {class: "form-control input-lg"}%>
 	</p>
	</div><br>

	<%= f.submit "Créer", class:"btn btn-primary" %>
	<%end%>


</div>