config/routes.rb
Rails.application.routes.draw do
	
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

	root "welcome#index"
	resources :annonces
	resources :categories
	get "/mes_annonces", to: "mes_annonces#index"
	get "/static/cgu", to: "static#cgu"
	get "/static/a_propos", to: "static#a_propos"
	get "/list", to: "static#list"
	get "admin", to: 'welcome#admin'
	get "contact", to: "contact#simple_form"
	resources :news

end

app/models/annonces.rb
class Annonces < ActiveRecord::Base

    validates :titre, presence: true,
                    length: { minimum: 5 }

    mount_uploader :image, ImageUploader
    
    validates :category_id, presence: true
    validates :type_id, presence: true

    belongs_to :categories
    belongs_to :user
    belongs_to :type

    validates :cgu,  :acceptance => {:accept => true}
    
	 def  self.search(search)
   		where("titre LIKE ?", "%#{search}%") 
  		where("description LIKE ?", "%#{search}%")
  	end

end

app/controllers/annonces_controller.rb
	class AnnoncesController < ApplicationController
	before_action :find_annonce, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]


	def index
		@check_annonce = Annonces.any?

	#filtrer la catégorie et le type de transaction

		if params[:categories].blank?
			@annonces = Annonces.all.order("created_at DESC")
		else
			@category_id = Categories.find_by(name: params[:categories]).id
			@annonces = Annonces.where(category_id: @category_id).order("created_at DESC")
		end

		if params[:type].blank?
			@annonces = Annonces.all.order("created_at DESC")
		else
			@type_id = Type.find_by(name: params[:type]).id
			@annonces = Annonces.where(type_id: @type_id).order("created_at DESC")
		end

	#barre de recherche
	
		if params[:search]
			@annonces = Annonces.search(params[:search]).order("created_at DESC")
		end
	end

	def show
		#Montrer la catégorie, la ville et le pseudo de l'annonceur dans la page de l'annonce
		@categorie = Categories.where(id: @annonce.category_id).pluck(:name)
		@categorie = @categorie.to_s
		@categorie = @categorie.tr('[]', '')
		@categorie = @categorie.tr('""', '')

		@type = Type.where(id: @annonce.type_id).pluck(:name)
		@type = @type.to_s
		@type = @type.tr('[]', '')
		@type = @type.tr('""', '')

		@ville = Ville.where(id: @annonce.ville_id).pluck(:nom_ville)
		@ville = @ville.to_s
		@ville = @ville.tr('[]', '')
		@ville = @ville.tr('""', '')

		@user_name = User.where(id: @annonce.user_id).pluck(:name)
		@user_name_string = @user_name.to_s
		@user_name_string = @user_name_string.tr('[]', '')
		@user_name_string = @user_name_string.tr('""', '')
	end

	def new
		@annonce = Annonces.new
	end

	def create
		@annonce = Annonces.new(annonce_params)
		@annonce.user_id = current_user.id
		if @annonce.save
			redirect_to @annonce, notice: "Annonce créée avec succès !"
		else
			render 'new', notice: "Oups ! Une erreur s'est produite..."
		end
	end

	def edit
		if @annonce.user_id == current_user.id || current_user.name == 'Admin'
		else
			redirect_to @annonce, notice: "Petit malin. Qu'essayez-vous de faire ?"	
		end
	end

	def update
		@annonce = Annonces.find(params[:id])

		if @annonce.update(annonce_params)
			redirect_to @annonce, notice: "Annonce éditée avec succès !"
		else
			render 'edit'
		end
	end

	def destroy
		if @annonce.user_id == current_user.id || current_user.name == 'Admin'
			@annonce.destroy
			redirect_to annonces_path, notice: "Annonce supprimée"
		else
			redirect_to @annonce, notice: "Petit malin. Qu'essayez-vous de faire ?"	
		end
	end

	private 
		def annonce_params
			params.require(:annonce).permit(:id, :titre, :description, :image, :telephone, :category_id, :user_id, :cgu, :type_id, :ville_id)
		end

	private
		def find_annonce
			@annonce = Annonces.find(params[:id])
		end

end

app/views/annonces/_form.html.erb
<div class="center-block">

<%= form_for :annonce, url:annonces_path do |f| %>
<% if @annonce.errors.any? %>

	<div id="error_explanation">
		 <h2>
        <%= pluralize(@annonce.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @annonce.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
	</div>

	<% end %>

	<div>
	<%= f.label :titre, "Titre *" %>
	<%= f.text_field :titre, {class: "form-control input-lg"} %>
	</div><br>

	<div>
	<%= f.label :categorie, "Catégorie *" %>
	<%= f.collection_select :category_id, Categories.all, :id, :name, {prompt: "Sélectionner une catégorie"},  {class: "form-control input-lg"}%>
	</div><br>

	<div>	
	<p>
    <%= f.label :type, "Type de transaction *" %><br>
    <%= f.collection_select :type_id, Type.all, :id, :name, {prompt: "Sélectionner un type de transaction"},  {class: "form-control input-lg"}%>
 	 </p>
	</div><br>

	<div>
	<p>
    <%= f.label :description, "Description *" %><br>
    <%= f.text_area :description,  {class: "form-control input-lg"}%>
 	 </p>
	</div><br>

	<div>
	<p>
    <%= f.label :telephone, "Téléphone" %><br>
    <%= f.text_field :telephone, {class: "form-control input-sm"}%>
 	 </p>
	</div><br>

	<div>
	<%= f.label :images, "Images", {class: "control-label"} %>
	<%= f.file_field :image, class: "file" %>
	</div><br>

	<div>
	<%= f.label :ville, "Ville" %>
	<%= f.collection_select :ville_id, Ville.all, :id, :nom_ville, {prompt: "Sélectionner une ville"},  {class: "form-control input-lg"}%>
	</div><br>
	<!--
	<%= f.label :ecole, "Ecole" %>
-->
	
	<div>
	<br>
	<%= f.label :cgu, "En créant cette annonce, vous vous engagez à respecter les conditions générales d'utilisateur" %>
	<%= f.check_box :cgu %> 
	</div>

	<%= f.submit "Créer", class:"btn btn-primary" %>
<% end %>

<%= link_to 'Retour', annonces_path %> <br>

</div>

app/views/annonces/edit.html.erb
<%
meta title: "Editer l'annonce-Fond'Atelier",
     description: "Editer l'annonce-Fond'Atelier"
%>

<div class="container">
	<div class="panel-group">
    <div class="panel panel-primary">
      <div class="panel-heading">Éditer annonce</div>
        <div class="panel-body">

	<%= form_for :annonce, url: annonce_path(@annonce), method: :patch do |f| %>
	
	<% if @annonce.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@annonce.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @annonce.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


	<div>
	<%= f.label :titre, "Titre" %>
	<%= f.text_field :titre, {class: "form-control input-lg"} %>
	</div><br>

	<div>
	<%= f.label :categorie, "Catégorie" %>
	<%= f.collection_select :category_id, Categories.all, :id, :name, {prompt: "Sélectionner une catégorie"},  {class: "form-control input-lg"}%>
	</div><br>

	<div>	
	<p>
    <%= f.label :type, "Type de transaction *" %><br>
    <%= f.collection_select :type_id, Type.all, :id, :name, {prompt: "Sélectionner un type de transaction"},  {class: "form-control input-lg"}%>
 	 </p>
	</div><br>

	<div>
	<p>
    <%= f.label :description, "Description*" %><br>
    <%= f.text_area :description,  {class: "form-control input-lg"}%>
 	 </p>
	</div><br>

	<div>
	<p>
    <%= f.label :telephone, "Téléphone" %><br>
    <%= f.text_field :telephone, {class: "form-control input-lg"}%>
 	 </p>
	</div><br>

	<div>
	<%= f.label :images, "Images", {class: "control-label"} %>
	<%= f.file_field :image, class: "file" %>
	</div><br>

	<div>
	<%= f.label :ville, "Ville" %>
	<%= f.collection_select :ville_id, Ville.all, :id, :nom_ville, {prompt: "Sélectionner une ville"},  {class: "form-control input-lg"}%>
	</div><br>	
	<!--
	<%= f.label :ecole, "Ecole" %>
-->

	<%= f.submit "Éditer", class:"btn btn-primary" %>
<% end %>

<%= link_to 'Retour', annonces_path %> <br>
</div>
      </div>
    </div>
</div>

app/views/annonces/index.html.erb
<%
meta title: "Liste des annonces-Fond'Atelier",
     description: "Liste des annonces-Fond'Atelier",
     keywords: "Liste des annonces-Fond'Atelier"     
%>

<div class="container">

	<%= form_tag(annonces_path, :method => "get", id: "search-form", class: 'form-inline', role: 'form') do %>
	<div class="form-group">
		<span class="glyphicon glyphicon-search"></span>
		<%= text_field_tag :search, params[:search], placeholder: "Que cherchez-vous ?", class: "form-control input-xlarge" %>
		<%= submit_tag "Recherche", class: "btn btn-default" %>
	<% end %>
 	</div>

	<%if params[:categories].blank? %>
	<h2 style:'text-align:center;'>Annonces les plus récentes</h2>
	<%else%>
	<h3>Annonces publiées dans la catégorie "<%= params[:categories] %>"</h3>
	<%end%>

<!-- Buttons filtrer annonces-->
<div class="btn-group inline pull-left"> 
	<div class="dropdown">
		<button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"> Catégories 
			<span class="caret"></span></button>
		<ul class="dropdown-menu">
			<% Categories.all.each do |categories| %> 	
			<li><%= link_to categories.name, annonces_path(categories: categories.name) %></li>
			<% end %>
		</ul>
	</div><br>

	<div class="dropdown">
		<button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"> Type de transaction 
			<span class="caret"></span></button>
		<ul class="dropdown-menu">
			<% Type.all.each do |type| %> 	
			<li><%= link_to type.name, annonces_path(type: type.name) %></li>
			<% end %>
		</ul>
	</div><br>
</div>


<!---->

<% if @check_annonce == true %>
	<table class='table table-hover'>
		<tr class="info">
			<th>Titre</th>
			<th>Description</th>
			<th>Catégorie</th>
			<th>Type de transaction</th>
			<th>Annonceur</th>
		</tr>
		<% @annonces.each do |annonce| %>
			<tr>
				<td><%= link_to annonce.titre, annonce %></td>
				<td><%= link_to annonce.description, annonce %></td>
				<td><%= Categories.where(id: annonce.category_id).pluck(:name).to_s.tr('[]', '').tr('""', '') %></td>
				<td><%= Type.where(id: annonce.type_id).pluck(:name).to_s.tr('[]', '').tr('""', '') %></td>
				<td><%=  User.where(id: annonce.user_id).pluck(:name).to_s.tr('[]', '').tr('""', '') %></td>
			</tr>
		<% end %>
	</table>

<% else %>
	<%if user_signed_in? %>
	<h3>Il n'y a pas encore d'annonce, <%= link_to 'postez une annonce', new_annonce_path %>.</h3>
	<%else%>
	<h2>Il n'y a pas encore d'annonce, <%= link_to 'connectez-vous', new_user_session_path %> pour poster une annonce.</h2>
	<%end%>
<% end %>


</div>

app/views/annonces/new.html.erb
<%
meta title: "Nouvelle annonce-Fond'Atelier",
     description: "Nouvelle annonce-Fond'Atelier"  
%>

<div class='container'>
	<div class="panel-group">
		<div class="panel panel-primary">
			<div class="panel-heading">Nouvelle annonce</div>
			<div class="panel-body">	
				<%= render 'form' %>
			</div>
	
		</div>

	</div>
</div>
	

app/views/annonces/show.html.erb
<%
meta title:  @annonce.titre + " - Fond'Atelier",
     description: @annonce.description,
     keywords: @annonce.description     
%>

<%meta og: {
  	image: @annonce.image.url,
 	description: @annonce.description,
 	title:  @annonce.titre + " - Fond'Atelier"
}%>

<div class="container">
<div class='row'>
<div class="col-md-6">
	<h2><%= @annonce.titre %></h2>

	<div>
	<h3>Catégorie</h3>
		<%= @categorie %>
	<br>
	</div>
	

	<div>
	<h3>Description</h3>
		<%= @annonce.description %>
	<br>
	</div>

	<div>
	<%if user_signed_in? %>
	<%if @annonce.telephone?%>
		
			<div>
			<h3>Téléphone</h3>
			<%= @annonce.telephone %>
			<br>
			</div>
		<%end%>
	<%else%>
		<h4> <%= link_to 'Connectez-vous', new_user_session_path %> pour voir les informations de cet annonceur afin de le contacter.</h4>	
	<%end%>
	</div>


	<% if user_signed_in? %>
		<% if current_user.id == @annonce.user_id || current_user.name == 'Admin'%>
			<div>
				<%= link_to "Editer", edit_annonce_path(@annonce) %> |
				<%= link_to "Supprimer", annonce_path, method: :delete, data: { confirm: "êtes vous sur ?"} %>
			</div>
		<%end%>
	<%end%>

	<%= link_to "Retour à la liste des annonces", annonces_path %>
	
</div>

<div class="col-md-6">
	

	<div>
		<h3><%= @type %> <span class='italic'>par <%= @user_name_string %></span></h3>
	</div>

	<div>
	<p>Crée le <%=I18n.l @annonce.created_at, format: :default%>
	<%if @annonce.ville_id? %>
			à <%= @ville %> </p>
			<br>
	
	<%end%>

	<div>
		<%= image_tag @annonce.image.url, :id => "image_annonce"%>
	<br>
	</div>
</div>
	
</div>

</div>
<!-- INUTILE
<p id="notice"><%= notice %></p> -->