config/routes.rb
Rails.application.routes.draw do
	
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

	root "welcome#index"
	resources :annonces
	resources :categories
	get "/mes_annonces", to: "mes_annonces#index"
	get "/static/cgu", to: "static#cgu"
	get "/static/a_propos", to: "static#a_propos"
	get "/list", to: "static#list"
	get "admin", to: 'welcome#admin'
	get "contact", to: "contact#simple_form"
	resources :news

end

app/models/annonces.rb
class Annonces < ActiveRecord::Base

    validates :titre, presence: true,
                    length: { minimum: 5 }

    mount_uploader :image, ImageUploader
    
    validates :category_id, presence: true
    validates :type_id, presence: true

    belongs_to :categories
    belongs_to :user
    belongs_to :type

    validates :cgu,  :acceptance => {:accept => true}
    
	 def  self.search(search)
   		where("titre LIKE ?", "%#{search}%") 
  		where("description LIKE ?", "%#{search}%")
  	end

end

app/models/categories.rb
class Categories < ActiveRecord::Base
	has_many :annonces
end

app/models/ecole.rb
class Ecole < ActiveRecord::Base
	has_many :annonces
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/statut.rb
class Statut < ActiveRecord::Base
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :annonces
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :omniauthable, :omniauth_providers => [:facebook]

has_many :annonces

	  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
	def self.from_omniauth(auth)
  		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    	user.email = auth.info.email
    	user.password = Devise.friendly_token[0,20]
    	user.name = auth.info.name   # assuming the user model has a name
  		end
	end

end

app/models/ville.rb
class Ville < ActiveRecord::Base
	has_many :annonces
end

app/controllers/annonces_controller.rb
	class AnnoncesController < ApplicationController
	before_action :find_annonce, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]


	def index
		@check_annonce = Annonces.any?

	#filtrer la catégorie et le type de transaction

		if params[:categories].blank?
			@annonces = Annonces.all.order("created_at DESC")
		else
			@category_id = Categories.find_by(name: params[:categories]).id
			@annonces = Annonces.where(category_id: @category_id).order("created_at DESC")
		end

		if params[:type].blank?
			@annonces = Annonces.all.order("created_at DESC")
		else
			@type_id = Type.find_by(name: params[:type]).id
			@annonces = Annonces.where(type_id: @type_id).order("created_at DESC")
		end

	#barre de recherche
	
		if params[:search]
			@annonces = Annonces.search(params[:search]).order("created_at DESC")
		end
	end

	def show
		#Montrer la catégorie, la ville et le pseudo de l'annonceur dans la page de l'annonce
		@categorie = Categories.where(id: @annonce.category_id).pluck(:name)
		@categorie = @categorie.to_s
		@categorie = @categorie.tr('[]', '')
		@categorie = @categorie.tr('""', '')

		@type = Type.where(id: @annonce.type_id).pluck(:name)
		@type = @type.to_s
		@type = @type.tr('[]', '')
		@type = @type.tr('""', '')

		@ville = Ville.where(id: @annonce.ville_id).pluck(:nom_ville)
		@ville = @ville.to_s
		@ville = @ville.tr('[]', '')
		@ville = @ville.tr('""', '')

		@user_name = User.where(id: @annonce.user_id).pluck(:name)
		@user_name_string = @user_name.to_s
		@user_name_string = @user_name_string.tr('[]', '')
		@user_name_string = @user_name_string.tr('""', '')
	end

	def new
		@annonce = Annonces.new
	end

	def create
		@annonce = Annonces.new(annonce_params)
		@annonce.user_id = current_user.id
		if @annonce.save
			redirect_to @annonce, notice: "Annonce créée avec succès !"
		else
			render 'new', notice: "Oups ! Une erreur s'est produite..."
		end
	end

	def edit
		if @annonce.user_id == current_user.id || current_user.name == 'Admin'
		else
			redirect_to @annonce, notice: "Petit malin. Qu'essayez-vous de faire ?"	
		end
	end

	def update
		@annonce = Annonces.find(params[:id])

		if @annonce.update(annonce_params)
			redirect_to @annonce, notice: "Annonce éditée avec succès !"
		else
			render 'edit'
		end
	end

	def destroy
		if @annonce.user_id == current_user.id || current_user.name == 'Admin'
			@annonce.destroy
			redirect_to annonces_path, notice: "Annonce supprimée"
		else
			redirect_to @annonce, notice: "Petit malin. Qu'essayez-vous de faire ?"	
		end
	end

	private 
		def annonce_params
			params.require(:annonce).permit(:id, :titre, :description, :image, :telephone, :category_id, :user_id, :cgu, :type_id, :ville_id)
		end

	private
		def find_annonce
			@annonce = Annonces.find(params[:id])
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:name, :statut_id, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
  helper_method :resource_name, :resource, :devise_mapping

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Merci pour votre message !'
    else
      flash.now[:error] = "Le message n'a pas pu être envoyé."
      render :new
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

	before_action :find_news, only: [:show, :edit, :update, :destroy]

	def index
		@new = News.all.order("created_at DESC")
	end

	def new
		@new = News.new
	end

	def create
		@new = News.new(news_params)
		if @new.save
			redirect_to news_index_path, notice: "Article créé avec succès !"
		else
			render 'new', notice: "Oups ! Une erreur s'est produite..."
		end
	end


	def edit
	end

	def update
		if @new.update(news_params)
			redirect_to @new, notice: "Article éditée avec succès !"
		else
			render 'edit'
		end
	end

	def show
		
	end

	def destroy
		@new.destroy
		redirect_to news_index_path, notice: "Article supprimée"
	end

	private 
		def news_params
			params.require(:news).permit(:id, :titre, :contenu)
		end

	private
		def find_news
			@new = News.find(params[:id])
		end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def cgu
	end

	def a_propos
	end

	def contact
		
	end

	def list
		if current_user.name == 'Admin' 
		else
			redirect_to root_path, notice: "Petit malin. Qu'essayez-vous de faire ?"	
		end
		@user = User.all.order(:id)
		@user_count = User.all.count
		@user_id = User.pluck(:id).to_s.tr('""', '')
		@user_email = User.pluck(:email).to_s.tr('""', '')
		@user_name = User.pluck(:name).to_s.tr('""', '')
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/mes_annonces_helper.rb
module MesAnnoncesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_footer.html.erb
	<div class="container-fluid">

		

				<%if user_signed_in?%>
					<% if current_user.name == 'Admin' %>
					<li>
					<%=link_to "Admin", admin_path, :class => 'navbar-link admin-link' %>
					</li>
					<%end%>
				<%end%>

				

				<li>	
				<%= link_to "Conditions générales", static_cgu_path,:class => 'navbar-link' %>
				</li>

				<li><%= link_to "Contact", new_contact_path, :class => 'navbar-link' %>
				</li>

		
		</div>

app/views/layouts/_header.html.erb
	
	<div class="container-fluid">
    	<div class="navbar-header">		
			
				<%= link_to root_path, :class => 'navbar-brand' do%>
				<img id="logo_header" src="../../assets/fondatelier_logo50.png">
				<%end%>
		</div>
			<% if user_signed_in? == false %>
			<ul class="nav navbar-nav navbar-left">
				<li>
				<%= link_to static_a_propos_path,:class => 'navbar-link' do%><span class="glyphicon glyphicon-info-sign"></span><%=" À propos"%><%end%>
				</li>
			</ul>
			<%end%>
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
				<li><p class="navbar-text">Connecté en tant que <strong><%= link_to edit_user_registration_path, :class => 'navbar-link' do %><%= current_user.name %></strong></p></li><%end%>
				<%end%>

				<li><%= link_to annonces_path, :class => 'navbar-link' do%><span class="glyphicon glyphicon-th-list"></span> <%= 'Liste des annonces'%>
				</li><%end%>

				<% if user_signed_in? %>

				<li><%= link_to mes_annonces_path,:class => 'navbar-link' do%><span class='glyphicon glyphicon-edit'></span> <%="Mes annonces"%>
				</li><%end%>
<!--
		  		<li><%= link_to 'Modifier votre profil', edit_user_registration_path, :class => 'navbar-link' %></li>-->
		  		<li><%= link_to destroy_user_session_path, method: :delete, :class => 'navbar-link' do%><span class='glyphicon glyphicon-off'></span> <%="Se déconnecter"%>
		  		</li><%end%>
				
				<li><%= link_to new_annonce_path do %><span class='glyphicon glyphicon-pencil'></span> 
					<%='Nouvelle annonce'%><li><%end%>

				<% else %>
				
				<!--
		  		<li><%= link_to new_user_registration_path, :class => 'navbar-link' do %><span class="glyphicon glyphicon-user"></span> <%= "Créer un compte" %>
		  		</li><% end %>

		  		
		  		<li><%= link_to new_user_session_path, :class => 'navbar-link' do%> <span class="glyphicon glyphicon-log-in"></span> <%= "S'identifier" %>
		  		</li><% end %>-->

		  		<input type="checkbox" name="toggle" id="toggle" />
				<label for="toggle"></label>
				<% if user_signed_in? == false%>

				<div class="message"><h2>Vous êtes nouveau sur Fond'Atelier ? <%= link_to new_user_registration_path, :id => 'new_registration' do %> <%="Créez un compte"%>
		  		<% end %> ou connectez-vous.</h2>
				
				<div class="form-group">
				<%= simple_form_for("user", :url => user_session_path) do |f| %>
  				<div class="form-inputs">
    			<%= f.input :email, required: false, autofocus: true, class: "form-control" %>
    			<%= f.input :password, required: false, class: "form-control" %>
    			
  				</div>
     	 		<%= f.button :submit, "S'identifier" %>
     	 		<%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
 		 		<% end %>
 		 		</div>
 		 		
 		 		<input type="checkbox" name="toggle" id="close" />
 				<label for="toggle"></label>

				</div>
				<%end%>
		
				<% end %>
			</ul>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
	<head>
		<%= metamagic %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<link href='https://fonts.googleapis.com/css?family=Montserrat:700' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=PT+Sans:400italic,400' rel='stylesheet' type='text/css'>
	</head>
	<div class="container">
	<div id="header">
		<%= render "layouts/header" %>
	</div>
		
	<div class="container-fluid">
		<% if notice %>
			<p class="alert alert-success"><%= notice %></p>
		<% end %>
		
		<% if alert %>
			<p class="alert alert-danger"><%= alert %></p>
		<% end %>
	</div>
	</div>

<body>
	<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '440291142841844',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

	<%= yield %>

	
	<div class="container">
		
		<div id="footer">
			<%= render "layouts/footer" %>
		</div>
	</div>
	
	
</body>

</html>